name: Deploy to GitHub Pages

# Run workflow on every push
on: 
  push:
    branches:
      - KKSunshine

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
      # uses GitHub's checkout action to checkout code form the master branch
      - uses: actions/checkout@v2

      # sets up .NET Core SDK
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      # publishes Blazor project to the release-folder
      - name: Publish .NET Core Project
        run: dotnet publish "SaveLoadCompressionWeb/SaveLoadCompressionWeb.csproj" -c Release -o release -p:PublishTrimmed=false --nologo

      # # changes the base-tag in index.html from '/' to 'BlazorGitHubPagesDemo' to match GitHub Pages repository subdirectory
      # - name: Change base-tag in index.html from / to BlazorGitHubPagesDemo
      #   run: sed -i 's/<base href="\/" \/>/<base href="\/BlazorGitHubPagesDemo\/" \/>/g' release/wwwroot/index.html

      # # changes the base-tag in index.html from '/' to 'BlazorGitHubPagesDemo' to match GitHub Pages repository subdirectory
      # - name: Fix service-worker-assets.js hashes
      #   working-directory: release/wwwroot
      #   run: |
      #     jsFile=$(<service-worker-assets.js)
      #     # remove JavaScript from contents so it can be interpreted as JSON
      #     json=$(echo "$jsFile" | sed "s/self.assetsManifest = //g" | sed "s/;//g")
      #     # grab the assets JSON array
      #     assets=$(echo "$json" | jq '.assets[]' -c)
      #     for asset in $assets
      #     do
      #       oldHash=$(echo "$asset" | jq '.hash')
      #       #remove leading and trailing quotes
      #       oldHash="${oldHash:1:-1}"
      #       path=$(echo "$asset" | jq '.url')
      #       #remove leading and trailing quotes
      #       path="${path:1:-1}"
      #       newHash="sha256-$(openssl dgst -sha256 -binary $path | openssl base64 -A)"

      #       if [ $oldHash != $newHash ]; then
      #         # escape slashes for json
      #         oldHash=$(echo "$oldHash" | sed 's;/;\\/;g')
      #         newHash=$(echo "$newHash" | sed 's;/;\\/;g')
      #         echo "Updating hash for $path from $oldHash to $newHash"
      #         # escape slashes second time for sed
      #         oldHash=$(echo "$oldHash" | sed 's;/;\\/;g')
      #         jsFile=$(echo -n "$jsFile" | sed "s;$oldHash;$newHash;g")
      #       fi
      #     done

      #     echo -n "$jsFile" > service-worker-assets.js

      # copy LICENSE.html
      - name: copy LICENSE.html
        run: cp LICENSE.html release/wwwroot/LICENSE.html

      # copy index.html to 404.html to serve the same file when a file is not found
      - name: copy index.html to 404.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html

      # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      # add CNAME file
      - name: Add CNAME file
        run: echo 'slcweb.maki0419.com' > release/wwwroot/CNAME

      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.CR_PAT }}
          BRANCH: gh-pages
          FOLDER: release/wwwroot
